# {\r\n    \"@context\": \"https:\/\/schema.org\",\r\n    \"@type\": \"Person\"\r\n  }
POST http://localhost:8005/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGYzM2QxMzhiMmVmYTk3N2M4ZWNhMGMiLCJlbWFpbCI6ImdlZ2VlbGVuQGdlZ2VlbnNvZnQuY29tIiwiaWF0IjoxNzYwOTQyMzU2LCJleHAiOjE3NjA5NDU5NTYsImF1ZCI6ImxvY2FsaG9zdDo4MDA1IiwiaXNzIjoibG9jYWxob3N0OjgwMDUifQ.GvehK3HsNGW4seu_CeVJ_fmXB-MAeYirS8xcd_Ua2Sk

{
  "title": "Astro js",
  "postType": "post",
  "slug": "new-with-nest-js-1",
  "status": "draft",
  "content": "post-content",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "publishOn": "2024-03-16T07:46:32.000+00:00",
  "tags": ["68eca92a1627ac2ef8cc6664"]
}
