PATCH http://localhost:8005/users/update-user-phone
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGYzM2QxMzhiMmVmYTk3N2M4ZWNhMGMiLCJlbWFpbCI6ImdlZ2VlbGVuQGdlZ2VlbnNvZnQuY29tIiwiaWF0IjoxNzYyMTUzMDUxLCJleHAiOjE3NjIxNTY2NTEsImF1ZCI6ImxvY2FsaG9zdDo4MDA1IiwiaXNzIjoibG9jYWxob3N0OjgwMDUifQ.q9nSgNjtFqoi3N5XcSNs9bjTDuqML8pLDji_Tk3PZ5o

{
  "phone": "99134731",
  "otp": "952206"
}
