POST http://localhost:8005/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGYzM2QxMzhiMmVmYTk3N2M4ZWNhMGMiLCJlbWFpbCI6ImdlZ2VlbGVuQGdlZ2VlbnNvZnQuY29tIiwiaWF0IjoxNzYwOTQ0MDQ1LCJleHAiOjE3NjA5NDc2NDUsImF1ZCI6ImxvY2FsaG9zdDo4MDA1IiwiaXNzIjoibG9jYWxob3N0OjgwMDUifQ.EtPfJXKhy4-xuNMKVDq5hpusoqtqd94VhSQbs5uDrck
{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGYzM2QxMzhiMmVmYTk3N2M4ZWNhMGMiLCJpYXQiOjE3NjA5NDQwNDUsImV4cCI6MTc2MTAzMDQ0NSwiYXVkIjoibG9jYWxob3N0OjgwMDUiLCJpc3MiOiJsb2NhbGhvc3Q6ODAwNSJ9.eG9uP_LWVesz_mUC5aOeqIWO_HAFN8q0XZzsykxcZ5Q"
}